### ISSUE TITLE
URLs don't work without explicit "http://www."

### ISSUE THREAD

**Issue by morgane** [software-workers-guild/nabu#3]
Typing in `wikipedia.org` won't do anything; I need the full URL (`http://www.wikipedia.org`). This is tedious to have to include.

**Comment by nickbytes** [comment]
Yea def need to do this. 

What do you think about this flow:

- type in something to the search bar
- we validate if this is a url
- if its a url, parse the page and show it
- if not a url, search on wikipedia

Maybe getting a little ahead of ourselves though, bc then would need to handle if theres no results on wikipedia

**Comment by morgane** [comment]
I like that flow, and I like having Wikipedia as a default.

> if theres no results on wikipedia

Whether we search on Wikipedia or not, we still need an error state. I think a simple screen that's like "Oops! Couldn't find what you were looking for. Try again? [hints]" would be enough
