### ISSUE TITLE
Browser needs better name

### ISSUE THREAD

**Issue by morgane** [software-workers-guild/nabu#4]
"nabu"? What even is that?

**Comment by nickbytes** [comment]
> Nabu was the patron god of scribes, literacy, and wisdom.[2] He was also the inventor of writing, a divine scribe, and the patron god of the rational arts.[3] Due to his role as an oracle, Nabu was associated with the Mesopotamian moon god Sin.[3]

Also

> Babylonian records of Mercury date back to the 1st millennium BC. The Babylonians called the planet Nabu after the messenger to the gods in their mythology

But yeaaaa I think it prob needs a better name

**Comment by morgane** [comment]
love that you're lowkey dunking on me rn

I don't have any other suggestions really so it can be Nabu

**Comment by morgane** [comment]
we got a nice ass name, no need to change it
